name: Build and Deploy to ECS

on:
  push:
    paths:
      - 'Web-App (Jokes Site)/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Web-App\ \(Jokes Site\)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/jokes-app:latest
          docker build -t $IMAGE_URI "./Web-App (Jokes Site)"
          docker push $IMAGE_URI

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster jokes-cluster \
            --service jokes-service \
            --force-new-deployment
