name: Destroy All Infra

on:
  push:
    branches:
      - destroy   

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destroy branch
        uses: actions/checkout@v3
        with:
          ref: destroy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Destroy everything
        run: |
          chmod +x destroy-all.sh
          ./destroy-all.sh
