name: Destroy All Infra

on:
  workflow_dispatch:   # <-- allows you to click “Run workflow” in the UI
  push:
    branches:
      - destroy

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the main branch so we have Infrastructure/
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    # 2. Fetch the destroy script from this branch
    - name: Fetch destroy script
      run: |
        git fetch origin destroy
        git checkout origin/destroy -- destroy-all.sh
        chmod +x destroy-all.sh

    # 3. Configure AWS creds
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ap-south-1

    # 4. Install Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    # 5. Run the destroy script
    - name: Run destroy script
      run: ./destroy-all.sh
