# .github/workflows/ci.yml

name: Full Infra + App CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION:        ap-south-1
  TF_BUCKET:         my-tf-state-bucket-rex-2025
  TF_DDB_TABLE:      my-tf-lock-table-rex-2025
  TF_STATE_KEY_FMT:  "${{ env.APP_NAME }}/terraform.tfstate"

  # Change this per app; can be set as a GitHub Secret or overwritten in each run
  APP_NAME:          jokes-app

  # Derived from APP_NAME:
  ECR_REPOSITORY:    ${{ env.APP_NAME }}
  ECS_CLUSTER:       ${{ env.APP_NAME }}-cluster
  ECS_SERVICE:       ${{ env.APP_NAME }}-service
  IMAGE_TAG:         latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ─────────────────────────────────────────────────────────────
    # 1) Checkout & AWS Credentials
    # ─────────────────────────────────────────────────────────────
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    # ─────────────────────────────────────────────────────────────
    # 2) Bootstrap Terraform Backend (S3 + DynamoDB)
    # ─────────────────────────────────────────────────────────────
    - name: Ensure S3 State Bucket exists
      run: |
        if ! aws s3api head-bucket --bucket "$TF_BUCKET" 2>/dev/null; then
          aws s3api create-bucket \
            --bucket "$TF_BUCKET" \
            --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
          aws s3api put-bucket-versioning \
            --bucket "$TF_BUCKET" \
            --versioning-configuration Status=Enabled
          echo "✔ Created backend bucket $TF_BUCKET"
        else
          echo "✔ Backend bucket $TF_BUCKET already exists"
        fi

    - name: Ensure DynamoDB Lock Table exists
      run: |
        if ! aws dynamodb describe-table --table-name "$TF_DDB_TABLE" 2>/dev/null; then
          aws dynamodb create-table \
            --table-name "$TF_DDB_TABLE" \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
          echo "✔ Created lock table $TF_DDB_TABLE"
        else
          echo "✔ Lock table $TF_DDB_TABLE already exists"
        fi

    # ─────────────────────────────────────────────────────────────
    # 3) Install Terraform
    # ─────────────────────────────────────────────────────────────
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    # ─────────────────────────────────────────────────────────────
    # 4) Terraform Init & Apply (Main Infrastructure)
    # ─────────────────────────────────────────────────────────────
    - name: Terraform Init & Apply
      working-directory: Infrastructure
      run: |
        terraform init \
          -backend-config="bucket=$TF_BUCKET" \
          -backend-config="key=${TF_STATE_KEY_FMT}" \
          -backend-config="region=$AWS_REGION" \
          -backend-config="dynamodb_table=$TF_DDB_TABLE"
        terraform apply -auto-approve

    # ─────────────────────────────────────────────────────────────
    # 5) Build & Push Docker Image to ECR
    # ─────────────────────────────────────────────────────────────
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Docker Image
      working-directory: Web-App\ \(Jokes\ Site\)
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    # ─────────────────────────────────────────────────────────────
    # 6) Deploy New Image to ECS
    # ─────────────────────────────────────────────────────────────
    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster "$ECS_CLUSTER" \
          --service "$ECS_SERVICE" \
          --force-new-deployment
